"""initial_schema

Revision ID: 8a18677e22b5
Revises: 
Create Date: 2026-06-17 14:36:58.098358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a18677e22b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('articles', 'published_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('articles', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_articles_processed'), table_name='articles')
    op.drop_index(op.f('idx_articles_published'), table_name='articles')
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=True)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.alter_column('digest_subscribers', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_digest_subscribers_id'), 'digest_subscribers', ['id'], unique=False)
    op.create_unique_constraint(None, 'digest_subscribers', ['email'])
    op.alter_column('event_statistics', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_event_statistics_id'), 'event_statistics', ['id'], unique=False)
    op.alter_column('event_types', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_event_types_id'), 'event_types', ['id'], unique=False)
    op.create_unique_constraint(None, 'event_types', ['name'])
    op.alter_column('events', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('events', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('events', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_events_date'), table_name='events')
    op.drop_index(op.f('idx_events_location'), table_name='events')
    op.drop_index(op.f('idx_events_type'), table_name='events')
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.alter_column('locations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('locations', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('locations', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_locations_state'), table_name='locations')
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.alter_column('risk_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_risk_snapshots_id'), 'risk_snapshots', ['id'], unique=False)
    op.alter_column('sources', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('sources', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.alter_column('states', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_unique_constraint(None, 'states', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'states', type_='unique')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.alter_column('states', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.alter_column('sources', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('sources', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_risk_snapshots_id'), table_name='risk_snapshots')
    op.alter_column('risk_snapshots', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.create_index(op.f('idx_locations_state'), 'locations', ['state_id'], unique=False)
    op.alter_column('locations', 'longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('locations', 'latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('locations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.create_index(op.f('idx_events_type'), 'events', ['event_type_id'], unique=False)
    op.create_index(op.f('idx_events_location'), 'events', ['location_id'], unique=False)
    op.create_index(op.f('idx_events_date'), 'events', ['event_date'], unique=False)
    op.alter_column('events', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('events', 'confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('events', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'event_types', type_='unique')
    op.drop_index(op.f('ix_event_types_id'), table_name='event_types')
    op.alter_column('event_types', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_event_statistics_id'), table_name='event_statistics')
    op.alter_column('event_statistics', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'digest_subscribers', type_='unique')
    op.drop_index(op.f('ix_digest_subscribers_id'), table_name='digest_subscribers')
    op.alter_column('digest_subscribers', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.create_index(op.f('idx_articles_published'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('idx_articles_processed'), 'articles', ['processed', 'extraction_status'], unique=False)
    op.alter_column('articles', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('articles', 'published_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('articles', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
